image: "ruby:2.5"

services:
  - redis:latest
  - postgres:latest

stages:
  - test
  - deploy_integration

variables:
  HOST: 'localhost'
  PORT: '4567'
  POSTGRES_DB: 'eleven_test'
  POSTGRES_HOST: 'postgres'
  POSTGRES_USER: 'runner'
  POSTGRES_PASSWORD: ''
  POSTGRES_PORT: '5432'
  DB_NAME: $POSTGRES_DB
  DB_HOST: $POSTGRES_HOST
  DB_USER: $POSTGRES_USER
  DB_PASSWORD: $POSTGRES_PASSWORD
  DB_PORT: $POSTGRES_PORT
  REDIS_HOST: 'redis'
  SIDEKIQ_REDIS_URL: redis://$REDIS_HOST:6379/0
  APP_VERSION: '1.0.0'
  APP_TYPE: "rails"

rspec:
  variables:
    RAILS_ENV: "test"
  stage: test
  script:
    - cp -f config/application.template.yml config/application.yml
    - gem install bundler
    - apt-get install ruby-dev
    - bundle install
    - bundle config build.nokogiri --use-system-libraries
    - bundle exec rake db:drop:all db:create:all db:migrate
    - bundle exec rspec

deploy_integration:
  stage: deploy_integration
  script:
    - echo "deploying integration"