---
version: 2.1

jobs:
  test:
    working_directory: ~/eleven
    docker:
      - image: circleci/ruby:2.5.5
        environment:
          RAILS_ENV: test
      - image: postgres:10.1-alpine
        environment:
          POSTGRES_USER: eleven
          POSTGRES_DB: eleven-test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - restore_cache:
          name: Restore bundle cache
          key: eleven-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          name: Store bundle cache
          key: eleven-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: cp .sample.env .env
      - run: gem update
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rake db:setup db:migrate
      - run: bundle exec rake

workflows:
  version: 2
  eleven:
    jobs:
      - test