---
version: 2.1
jobs:
  build:
    working_directory: ~/your-app-name
    docker:
      - image: circleci/ruby:2.5.5
        environment:
          RAILS_ENV: test
      - image: postgres:10.1-alpine
        environment:
          POSTGRES_USER: eleven
          POSTGRES_DB: eleven-test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: cp .sample.env .env
      - run: gem update
      - run: gem install bundler
      - run: bundle exec rake db:setup db:migrate
      - run: bundle exec rake