---
version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

jobs:
  test:
    working_directory: ~/eleven
    docker:
      - image: circleci/ruby:2.5.5
        environment:
          RAILS_ENV: test
      - image: postgres:10.1-alpine
        environment:
          POSTGRES_USER: eleven
          POSTGRES_DB: eleven-test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: cp config/application.template.yml config/application.yml
      - run: gem update
      - run: gem install bundler
      - restore_cache:
          name: Restore bundle cache
          key: eleven-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          name: Store bundle cache
          key: eleven-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: bundle exec rails db:migrate
      - run: bundle exec rake
  deploy_staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master
      - heroku run rails db:migrate --app $HEROKU_APP_NAME

workflows:
  version: 2
  eleven:
    jobs:
      - test
      - deploy_staging:
          requires:
            - test
          filters:
            branches:
              only: master