HOST: 'localhost'
PORT: '8080'
RAILS_MAX_THREADS: '3'

SIDEKIQ_REDIS_URL: 'redis://localhost:6379/0'

DB_NAME: 'eleven'
DB_HOST: 'localhost'
DB_PORT: '5432'
DB_USER: 'eleven'
DB_PASSWORD: ''

ELEVEN_EMAIL_USERNAME: 'eleven.el.sg@gmail.com'
ELEVEN_EMAIL_PASSWORD: ''

GOOGLE_STORAGE_ACCESS_KEY_ID: ''
GOOGLE_STORAGE_SECRET_ACCESS_KEY: ''

GCP_CLOUD_VISION_API_KEY: ''
GCP_CLOUD_VISION_BASE_URL: ''