default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  host: <%= Figaro.env.db_host %>
  username: <%= Figaro.env.db_user %>
  password: <%= Figaro.env.db_password %>
  port: <%= Figaro.env.db_port %>
  database: eleven_dev

test: &test
  <<: *default
  host: <%= Figaro.env.db_host %>
  username: <%= Figaro.env.db_user %>
  password: <%= Figaro.env.db_password %>
  port: <%= Figaro.env.db_port %>
  database: eleven_test

production:
  <<: *default
  url: <%= Figaro.env.database_url %>

cucumber:
  <<: *test