app:
  name: "eleven"

replicaCount: 1

ingress:
  enabled: false

image:
  name: "eleven"
  repository: "weewey/eleven"
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}